language: php

php:
    - 7.2
    - 7.3
    - 7.4

before_install:
    - composer self-update --no-interaction

install:
    - composer install --no-interaction --prefer-source

script:
    - vendor/bin/rector process -v --ansi --autoload-file vendor/autoload.php --config rector.yaml src --dry-run

after_script:
    - vendor/bin/phpstan analyze --level=max src/
