language: php

php:
    - 7.2
    - 7.3
    - 7.4

install:
    - composer install --no-interaction --prefer-source

script:
    - vendor/bin/rector process src --dry-run

after_script:
    - vendor/bin/phpstan analyze --level max src
