#!/bin/bash

# This fails
echo "Run through rector.phar inside Docker"
docker build -q -t rector_phar .
docker run --rm -v $(pwd):/app rector_phar process -v --ansi --autoload-file /app/vendor/autoload.php --config /app/rector.yaml /app/src --dry-run

# This works
echo "Run through rector.phar on your machine"
php rector.phar process -v --ansi --autoload-file vendor/autoload.php --config rector.yaml src --dry-run
