#!/bin/bash

echo "Run PhpStan"
php vendor/bin/phpstan analyze -c phpstan.neon

echo "Run Rector"
php vendor/bin/rector process --dry-run -v --ansi --autoload-file vendor/autoload.php --config rector.yaml src
